create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  visible boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.product_category_links (
  product_id text not null,
  category_id bigint not null references public.product_categories(id) on delete cascade,
  primary key (product_id, category_id)
);

alter table public.product_categories enable row level security;
alter table public.product_category_links enable row level security;
