'use client';import{useEffect,useState}from'react';
const socialDefs=[['instagram','Instagram'],['tiktok','TikTok'],['facebook','Facebook'],['pinterest','Pinterest'],['youtube','YouTube']];
export default function Admin(){const[s,setS]=useState(null),[msg,setMsg]=useState(''),[tab,setTab]=useState('vinted');useEffect(()=>{fetch('/api/settings').then(r=>r.json()).then(setS)},[]);if(!s)return <main className="admin"><p>Chargement…</p></main>;
 const change=(k,v)=>setS({...s,[k]:v});async function save(){setMsg('Enregistrement…');const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)}),j=await r.json();setMsg(j.message);if(j.settings)setS(j.settings)}
 async function upload(kind,file,key){if(!file)return;setMsg('Envoi de l’image…');let f=new FormData();f.append('kind',kind);f.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:f}),j=await r.json();if(j.ok){const ns={...s,[key]:j.url};setS(ns);const sr=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(ns)}),sj=await sr.json();setMsg(sj.message||'Image enregistrée.')}else setMsg(j.message)}
 async function capture(){setMsg('Création du nouvel aperçu…');const r=await fetch('/api/vinted-preview',{method:'POST'}),j=await r.json();setMsg(j.message);if(j.ok&&j.url)setS({...s,preview_desktop_url:j.url,desktop_separate:true})}
 return <main className="admin"><a href="/">← Retour au site</a><h1>Administration</h1><div className="adminTabs">{[['vinted','Aperçu Vinted'],['identity','Logo & identité'],['texts','Textes'],['socials','Réseaux sociaux']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
 {tab==='vinted'&&<div className="panel"><h2>Aperçu de la boutique Vinted</h2><button className="button" onClick={capture}>📸 Actualiser l’aperçu Vinted</button><p className="hint">Si Vinted bloque la tentative, la dernière image enregistrée reste affichée.</p><hr/><label className="uploadLabel"><strong>Capture téléphone</strong><span>Choisir une capture depuis le téléphone</span><input type="file" accept="image/*" onChange={e=>upload('preview_mobile',e.target.files[0],'preview_mobile_url')}/></label>{s.preview_mobile_url&&<img className="adminImage" src={s.preview_mobile_url}/>}<hr/><label className="switchrow"><span><strong>Utiliser une image différente sur ordinateur</strong><small>Le site choisira automatiquement l’image selon l’écran.</small></span><input type="checkbox" checked={!!s.desktop_separate} onChange={e=>change('desktop_separate',e.target.checked)}/></label>{s.desktop_separate&&<><label className="uploadLabel"><strong>Capture ordinateur</strong><input type="file" accept="image/*" onChange={e=>upload('preview_desktop',e.target.files[0],'preview_desktop_url')}/></label>{s.preview_desktop_url&&<img className="adminImage wide" src={s.preview_desktop_url}/>}</>}<label>Adresse de la boutique Vinted<input value={s.vinted_url||''} onChange={e=>change('vinted_url',e.target.value)}/></label><button className="button save" onClick={save}>Enregistrer</button></div>}
 {tab==='identity'&&<div className="panel"><h2>Logo & identité</h2><p>Le nom BoutchouBabioles reste affiché à côté du logo.</p><label className="uploadLabel"><strong>Logo</strong><span>Utilisé dans l’en-tête et comme icône du navigateur.</span><input type="file" accept="image/*" onChange={e=>upload('logo',e.target.files[0],'logo_url')}/></label>{s.logo_url&&<img className="adminLogo" src={s.logo_url}/>}<hr/><label className="uploadLabel"><strong>Image de partage réseaux sociaux</strong><span>Image affichée lors du partage du lien sur les réseaux compatibles.</span><input type="file" accept="image/*" onChange={e=>upload('social',e.target.files[0],'social_image_url')}/></label>{s.social_image_url&&<img className="adminImage wide" src={s.social_image_url}/>}</div>}
 {tab==='texts'&&<div className="panel formGrid"><h2>Textes du site</h2><label>Titre d’accueil<input value={s.hero_title||''} onChange={e=>change('hero_title',e.target.value)}/></label><label>Présentation<textarea value={s.hero_text||''} onChange={e=>change('hero_text',e.target.value)}/></label><label>Titre boutique<input value={s.shop_title||''} onChange={e=>change('shop_title',e.target.value)}/></label><label>Texte boutique<textarea value={s.shop_text||''} onChange={e=>change('shop_text',e.target.value)}/></label><label>Titre À propos<input value={s.about_title||''} onChange={e=>change('about_title',e.target.value)}/></label><label>Texte À propos<textarea rows="7" value={s.about_text||''} onChange={e=>change('about_text',e.target.value)}/></label><label className="uploadLabel"><strong>Photo À propos</strong><input type="file" accept="image/*" onChange={e=>upload('about',e.target.files[0],'about_image_url')}/></label><button className="button" onClick={save}>Enregistrer les textes</button></div>}
 {tab==='socials'&&<div className="panel"><h2>Réseaux sociaux</h2>{socialDefs.map(([k,n])=><div className="socialRow" key={k}><label className="switchrow"><span><strong>{n}</strong><small>Afficher sur le site</small></span><input type="checkbox" checked={!!s[k+'_enabled']} onChange={e=>change(k+'_enabled',e.target.checked)}/></label><input placeholder={`Lien ${n}`} value={s[k+'_url']||''} onChange={e=>change(k+'_url',e.target.value)}/></div>)}<button className="button" onClick={save}>Enregistrer les réseaux</button></div>}{msg&&<p className="status stickyStatus">{msg}</p>}</main>}
