'use client';import{useEffect,useMemo,useState}from'react';
const socialDefs=[['instagram','Instagram'],['tiktok','TikTok'],['facebook','Facebook'],['pinterest','Pinterest'],['youtube','YouTube']];
export default function Admin(){const[s,setS]=useState(null),[msg,setMsg]=useState(''),[tab,setTab]=useState('products'),[products,setProducts]=useState([]),[vis,setVis]=useState({}),[cats,setCats]=useState([]),[links,setLinks]=useState({}),[filter,setFilter]=useState('all'),[q,setQ]=useState(''),[newCat,setNewCat]=useState('');
async function reloadCats(){const[c,l]=await Promise.all([fetch('/api/categories').then(r=>r.json()),fetch('/api/product-categories').then(r=>r.json())]);setCats(c);setLinks(l)}
useEffect(()=>{fetch('/api/settings').then(r=>r.json()).then(setS);Promise.all([fetch('/api/products').then(r=>r.json()),fetch('/api/product-visibility').then(r=>r.json()),fetch('/api/categories').then(r=>r.json()),fetch('/api/product-categories').then(r=>r.json())]).then(([p,v,c,l])=>{setProducts(p);setVis(v);setCats(c);setLinks(l)})},[]);
const shown=useMemo(()=>products.filter(p=>{const on=vis[String(p.id)]!==false;if(filter==='shown'&&!on)return false;if(filter==='hidden'&&on)return false;return (p.title+' '+(p.brand||'')+' '+p.id).toLowerCase().includes(q.toLowerCase())}),[products,vis,filter,q]);
if(!s)return <main className="admin"><p>Chargement…</p></main>;
const change=(k,v)=>setS({...s,[k]:v});async function save(){setMsg('Enregistrement…');const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)}),j=await r.json();setMsg(j.message);if(j.settings)setS(j.settings)}
async function toggle(p,on){setVis(v=>({...v,[String(p.id)]:on}));const j=await fetch('/api/product-visibility',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:String(p.id),visible:on})}).then(r=>r.json());setMsg(j.ok?(on?'Article affiché sur le site.':'Article masqué du site.'):(j.message||'Erreur'))}
async function setProductCat(p,cid,on){const id=String(p.id),old=links[id]||[],next=on?[...new Set([...old,String(cid)])]:old.filter(x=>x!==String(cid));setLinks(x=>({...x,[id]:next}));const j=await fetch('/api/product-categories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:id,category_ids:next})}).then(r=>r.json());setMsg(j.message||'Enregistré.')}
async function addCat(){if(!newCat.trim())return;const j=await fetch('/api/categories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:newCat,visible:true,sort_order:cats.length})}).then(r=>r.json());setMsg(j.message);setNewCat('');await reloadCats()}
async function saveCat(c,patch={}){const n={...c,...patch};setCats(a=>a.map(x=>x.id===c.id?n:x));const j=await fetch('/api/categories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(n)}).then(r=>r.json());setMsg(j.message)}
async function delCat(c){if(!confirm('Supprimer cette catégorie ? Les produits ne seront pas supprimés.'))return;const j=await fetch('/api/categories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',id:c.id})}).then(r=>r.json());setMsg(j.message);await reloadCats()}
async function upload(kind,file,key){if(!file)return;setMsg('Envoi de l’image…');let f=new FormData();f.append('kind',kind);f.append('file',file);const j=await fetch('/api/upload',{method:'POST',body:f}).then(r=>r.json());if(j.ok){const ns={...s,[key]:j.url};setS(ns);const sj=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(ns)}).then(r=>r.json());setMsg(sj.message||'Image enregistrée.')}else setMsg(j.message)}
return <main className="admin"><a href="/">← Retour au site</a><h1>Administration</h1><div className="adminTabs">{[['products','Produits'],['categories','Catégories'],['identity','Logo & identité'],['texts','Textes'],['socials','Réseaux sociaux']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
{tab==='products'&&<div className="panel"><h2>Produits</h2><p className="hint">Affichage rapide et classement dans une ou plusieurs catégories.</p><div className="productTools"><input placeholder="Rechercher par nom, marque ou ID…" value={q} onChange={e=>setQ(e.target.value)}/><div className="filterBtns">{[['all','Tous'],['shown','Affichés'],['hidden','Masqués']].map(x=><button key={x[0]} className={filter===x[0]?'active':''} onClick={()=>setFilter(x[0])}>{x[1]}</button>)}</div></div><div className="productAdminList">{shown.map(p=>{const on=vis[String(p.id)]!==false,pc=links[String(p.id)]||[];return <div className={'productAdminRow '+(!on?'isHidden':'')} key={p.id}><img src={p.image}/><div className="productAdminInfo"><strong>{p.title}</strong><small>{p.brand||'BoutchouBabioles'} · {String(p.price).replace('.',',')} €</small><div className="productCats">{cats.map(c=><label key={c.id}><input type="checkbox" checked={pc.includes(String(c.id))} onChange={e=>setProductCat(p,c.id,e.target.checked)}/>{c.name}</label>)}</div></div><label className="quickToggle"><span>{on?'Affiché':'Masqué'}</span><input type="checkbox" checked={on} onChange={e=>toggle(p,e.target.checked)}/></label></div>})}</div></div>}
{tab==='categories'&&<div className="panel"><h2>Catégories</h2><p className="hint">Les catégories visibles apparaissent juste au-dessus des premières photos de la boutique.</p><div className="newCategory"><input placeholder="Nom de la nouvelle catégorie" value={newCat} onChange={e=>setNewCat(e.target.value)}/><button className="button" onClick={addCat}>+ Ajouter</button></div><div className="categoryAdminList">{cats.map((c,i)=><div className="categoryAdminRow" key={c.id}><input value={c.name} onChange={e=>setCats(a=>a.map(x=>x.id===c.id?{...x,name:e.target.value}:x))} onBlur={()=>saveCat(c,{name:(cats.find(x=>x.id===c.id)||c).name})}/><label><input type="checkbox" checked={!!c.visible} onChange={e=>saveCat(c,{visible:e.target.checked})}/> Visible</label><input className="orderInput" type="number" value={c.sort_order??i} onChange={e=>saveCat(c,{sort_order:Number(e.target.value)})}/><button className="deleteCat" onClick={()=>delCat(c)}>Supprimer</button></div>)}</div></div>}
{tab==='identity'&&<div className="panel"><h2>Logo & identité</h2><label className="uploadLabel"><strong>Logo</strong><input type="file" accept="image/*" onChange={e=>upload('logo',e.target.files[0],'logo_url')}/></label>{s.logo_url&&<img className="adminLogo" src={s.logo_url}/>}<label className="uploadLabel"><strong>Image de partage réseaux sociaux</strong><input type="file" accept="image/*" onChange={e=>upload('social',e.target.files[0],'social_image_url')}/></label>{s.social_image_url&&<img className="adminImage wide" src={s.social_image_url}/>}</div>}
{tab==='texts'&&<div className="panel formGrid"><h2>Textes du site</h2><label>Titre d’accueil<input value={s.hero_title||''} onChange={e=>change('hero_title',e.target.value)}/></label><label>Présentation<textarea value={s.hero_text||''} onChange={e=>change('hero_text',e.target.value)}/></label><label>Titre boutique<input value={s.shop_title||''} onChange={e=>change('shop_title',e.target.value)}/></label><label>Texte boutique<textarea value={s.shop_text||''} onChange={e=>change('shop_text',e.target.value)}/></label><button className="button" onClick={save}>Enregistrer les textes</button></div>}
{tab==='socials'&&<div className="panel"><h2>Réseaux sociaux</h2>{socialDefs.map(([k,n])=><div className="socialRow" key={k}><label className="switchrow"><span><strong>{n}</strong><small>Afficher sur le site</small></span><input type="checkbox" checked={!!s[k+'_enabled']} onChange={e=>change(k+'_enabled',e.target.checked)}/></label><input placeholder={'Lien '+n} value={s[k+'_url']||''} onChange={e=>change(k+'_url',e.target.value)}/></div>)}<button className="button" onClick={save}>Enregistrer les réseaux</button></div>}{msg&&<p className="status stickyStatus">{msg}</p>}</main>}