create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  product_id text,
  product_title text,
  created_at timestamptz not null default now()
);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_type_idx on public.analytics_events(event_type);
alter table public.analytics_events enable row level security;
